/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    NumberPlateTwoRow: THREE.Mesh;
    NumberPlateOneRow: THREE.Mesh;
    SampleNumberPlateTwoRow: THREE.Mesh;
    DecalAlphabet_A002: THREE.Mesh;
    DecalAlphabet_B002: THREE.Mesh;
    DecalAlphabet_Y002: THREE.Mesh;
    DecalNumber_3002: THREE.Mesh;
    DecalNumber_4002: THREE.Mesh;
    DecalNumber_6002: THREE.Mesh;
    DecalNumber_7002: THREE.Mesh;
    SampleNumberPlateOneRow: THREE.Mesh;
    DecalAlphabet_A001: THREE.Mesh;
    DecalAlphabet_B001: THREE.Mesh;
    DecalAlphabet_Y001: THREE.Mesh;
    DecalNumber_3001: THREE.Mesh;
    DecalNumber_4001: THREE.Mesh;
    DecalNumber_6001: THREE.Mesh;
    DecalNumber_7001: THREE.Mesh;
    ["3"]: THREE.Mesh;
    ["7"]: THREE.Mesh;
    C: THREE.Mesh;
    E: THREE.Mesh;
    G: THREE.Mesh;
    K: THREE.Mesh;
    L: THREE.Mesh;
    R: THREE.Mesh;
    S: THREE.Mesh;
    U: THREE.Mesh;
    ["1"]: THREE.Mesh;
    ["8"]: THREE.Mesh;
    H: THREE.Mesh;
    M: THREE.Mesh;
    P: THREE.Mesh;
    Q: THREE.Mesh;
    T: THREE.Mesh;
    V: THREE.Mesh;
    ["0"]: THREE.Mesh;
    F: THREE.Mesh;
    J: THREE.Mesh;
    N: THREE.Mesh;
    ["5"]: THREE.Mesh;
    ["6"]: THREE.Mesh;
    B: THREE.Mesh;
    I: THREE.Mesh;
    X: THREE.Mesh;
    ["4"]: THREE.Mesh;
    W: THREE.Mesh;
    Z: THREE.Mesh;
    ["9"]: THREE.Mesh;
    D: THREE.Mesh;
    ["2"]: THREE.Mesh;
    A: THREE.Mesh;
    O: THREE.Mesh;
    Y: THREE.Mesh;
    DecalAlphabet_W: THREE.Mesh;
    DecalNumber_0: THREE.Mesh;
    DecalNumber_6: THREE.Mesh;
    DecalAlphabet_D: THREE.Mesh;
    DecalAlphabet_B: THREE.Mesh;
    DecalAlphabet_H: THREE.Mesh;
    DecalAlphabet_I: THREE.Mesh;
    DecalAlphabet_L: THREE.Mesh;
    DecalAlphabet_S: THREE.Mesh;
    DecalAlphabet_V: THREE.Mesh;
    DecalNumber_5: THREE.Mesh;
    DecalAlphabet_A: THREE.Mesh;
    DecalAlphabet_R: THREE.Mesh;
    DecalAlphabet_N: THREE.Mesh;
    DecalAlphabet_Q: THREE.Mesh;
    DecalAlphabet_Y: THREE.Mesh;
    DecalNumber_3: THREE.Mesh;
    DecalAlphabet_J: THREE.Mesh;
    DecalAlphabet_T: THREE.Mesh;
    DecalNumber_1: THREE.Mesh;
    DecalNumber_4: THREE.Mesh;
    DecalAlphabet_G: THREE.Mesh;
    DecalAlphabet_O: THREE.Mesh;
    DecalAlphabet_Z: THREE.Mesh;
    DecalNumber_7: THREE.Mesh;
    DecalAlphabet_C: THREE.Mesh;
    DecalAlphabet_E: THREE.Mesh;
    DecalAlphabet_F: THREE.Mesh;
    DecalAlphabet_K: THREE.Mesh;
    DecalAlphabet_P: THREE.Mesh;
    DecalAlphabet_U: THREE.Mesh;
    DecalAlphabet_X: THREE.Mesh;
    DecalNumber_9: THREE.Mesh;
    DecalAlphabet_M: THREE.Mesh;
    DecalNumber_2: THREE.Mesh;
    DecalNumber_8: THREE.Mesh;
  };
  materials: {
    ["Number plate"]: THREE.MeshStandardMaterial;
    ["Decal number plate"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/alphabet.gltf"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.NumberPlateTwoRow.geometry}
        material={materials["Number plate"]}
        position={[-0.22, 0, 0]}
      />
      <mesh
        geometry={nodes.NumberPlateOneRow.geometry}
        material={materials["Number plate"]}
        position={[-0.22, 0.19, 0]}
      />
      <mesh
        geometry={nodes.SampleNumberPlateTwoRow.geometry}
        material={materials["Number plate"]}
        position={[-0.22, 0.3, 0]}
      >
        <mesh
          geometry={nodes.DecalAlphabet_A002.geometry}
          material={materials["Decal number plate"]}
          position={[-0.03, 0.07, 0]}
        />
        <mesh
          geometry={nodes.DecalAlphabet_B002.geometry}
          material={materials["Decal number plate"]}
          position={[0, 0.07, 0]}
        />
        <mesh
          geometry={nodes.DecalAlphabet_Y002.geometry}
          material={materials["Decal number plate"]}
          position={[0.04, 0.07, 0]}
        />
        <mesh
          geometry={nodes.DecalNumber_3002.geometry}
          material={materials["Decal number plate"]}
          position={[-0.05, 0.01, 0]}
        />
        <mesh
          geometry={nodes.DecalNumber_4002.geometry}
          material={materials["Decal number plate"]}
          position={[0.02, 0.01, 0]}
        />
        <mesh
          geometry={nodes.DecalNumber_6002.geometry}
          material={materials["Decal number plate"]}
          position={[-0.02, 0.01, 0]}
        />
        <mesh
          geometry={nodes.DecalNumber_7002.geometry}
          material={materials["Decal number plate"]}
          position={[0.05, 0.01, 0]}
        />
      </mesh>
      <mesh
        geometry={nodes.SampleNumberPlateOneRow.geometry}
        material={materials["Number plate"]}
        position={[-0.22, 0.47, 0]}
      >
        <mesh
          geometry={nodes.DecalAlphabet_A001.geometry}
          material={materials["Decal number plate"]}
          position={[-0.11, 0, 0]}
        />
        <mesh
          geometry={nodes.DecalAlphabet_B001.geometry}
          material={materials["Decal number plate"]}
          position={[-0.07, 0, 0]}
        />
        <mesh
          geometry={nodes.DecalAlphabet_Y001.geometry}
          material={materials["Decal number plate"]}
          position={[-0.04, 0, 0]}
        />
        <mesh
          geometry={nodes.DecalNumber_3001.geometry}
          material={materials["Decal number plate"]}
          position={[0.01, 0, 0]}
        />
        <mesh
          geometry={nodes.DecalNumber_4001.geometry}
          material={materials["Decal number plate"]}
          position={[0.08, 0, 0]}
        />
        <mesh
          geometry={nodes.DecalNumber_6001.geometry}
          material={materials["Decal number plate"]}
          position={[0.04, 0, 0]}
        />
        <mesh
          geometry={nodes.DecalNumber_7001.geometry}
          material={materials["Decal number plate"]}
          position={[0.11, 0, 0]}
        />
      </mesh>
      <mesh
        geometry={nodes["3"].geometry}
        material={materials["Number plate"]}
        position={[0.08, 0.51, 0.01]}
      />
      <mesh
        geometry={nodes["7"].geometry}
        material={materials["Number plate"]}
        position={[0.24, 0.51, 0.01]}
      />
      <mesh
        geometry={nodes.C.geometry}
        material={materials["Number plate"]}
        position={[0.1, 0.44, 0.01]}
      />
      <mesh
        geometry={nodes.E.geometry}
        material={materials["Number plate"]}
        position={[0.2, 0.44, 0.01]}
      />
      <mesh
        geometry={nodes.G.geometry}
        material={materials["Number plate"]}
        position={[0.3, 0.44, 0.01]}
      />
      <mesh
        geometry={nodes.K.geometry}
        material={materials["Number plate"]}
        position={[0, 0.37, 0.01]}
      />
      <mesh
        geometry={nodes.L.geometry}
        material={materials["Number plate"]}
        position={[0.05, 0.37, 0.01]}
      />
      <mesh
        geometry={nodes.R.geometry}
        material={materials["Number plate"]}
        position={[0.35, 0.37, 0.01]}
      />
      <mesh
        geometry={nodes.S.geometry}
        material={materials["Number plate"]}
        position={[0.4, 0.37, 0.01]}
      />
      <mesh
        geometry={nodes.U.geometry}
        material={materials["Number plate"]}
        position={[0, 0.3, 0.01]}
      />
      <mesh
        geometry={nodes["1"].geometry}
        material={materials["Number plate"]}
        position={[0, 0.51, 0.01]}
      />
      <mesh
        geometry={nodes["8"].geometry}
        material={materials["Number plate"]}
        position={[0.27, 0.51, 0.01]}
      />
      <mesh
        geometry={nodes.H.geometry}
        material={materials["Number plate"]}
        position={[0.35, 0.44, 0.01]}
      />
      <mesh
        geometry={nodes.M.geometry}
        material={materials["Number plate"]}
        position={[0.1, 0.37, 0.01]}
      />
      <mesh
        geometry={nodes.P.geometry}
        material={materials["Number plate"]}
        position={[0.25, 0.37, 0.01]}
      />
      <mesh
        geometry={nodes.Q.geometry}
        material={materials["Number plate"]}
        position={[0.3, 0.37, 0.01]}
      />
      <mesh
        geometry={nodes.T.geometry}
        material={materials["Number plate"]}
        position={[0.45, 0.37, 0.01]}
      />
      <mesh
        geometry={nodes.V.geometry}
        material={materials["Number plate"]}
        position={[0.05, 0.3, 0.01]}
      />
      <mesh
        geometry={nodes["0"].geometry}
        material={materials["Number plate"]}
        position={[0.35, 0.51, 0.01]}
      />
      <mesh
        geometry={nodes.F.geometry}
        material={materials["Number plate"]}
        position={[0.25, 0.44, 0.01]}
      />
      <mesh
        geometry={nodes.J.geometry}
        material={materials["Number plate"]}
        position={[0.45, 0.44, 0.01]}
      />
      <mesh
        geometry={nodes.N.geometry}
        material={materials["Number plate"]}
        position={[0.15, 0.37, 0.01]}
      />
      <mesh
        geometry={nodes["5"].geometry}
        material={materials["Number plate"]}
        position={[0.16, 0.51, 0.01]}
      />
      <mesh
        geometry={nodes["6"].geometry}
        material={materials["Number plate"]}
        position={[0.2, 0.51, 0.01]}
      />
      <mesh
        geometry={nodes.B.geometry}
        material={materials["Number plate"]}
        position={[0.05, 0.44, 0.01]}
      />
      <mesh
        geometry={nodes.I.geometry}
        material={materials["Number plate"]}
        position={[0.4, 0.44, 0.01]}
      />
      <mesh
        geometry={nodes.X.geometry}
        material={materials["Number plate"]}
        position={[0.15, 0.3, 0.01]}
      />
      <mesh
        geometry={nodes["4"].geometry}
        material={materials["Number plate"]}
        position={[0.12, 0.51, 0.01]}
      />
      <mesh
        geometry={nodes.W.geometry}
        material={materials["Number plate"]}
        position={[0.1, 0.3, 0.01]}
      />
      <mesh
        geometry={nodes.Z.geometry}
        material={materials["Number plate"]}
        position={[0.25, 0.3, 0.01]}
      />
      <mesh
        geometry={nodes["9"].geometry}
        material={materials["Number plate"]}
        position={[0.31, 0.51, 0.01]}
      />
      <mesh
        geometry={nodes.D.geometry}
        material={materials["Number plate"]}
        position={[0.15, 0.44, 0.01]}
      />
      <mesh
        geometry={nodes["2"].geometry}
        material={materials["Number plate"]}
        position={[0.04, 0.51, 0.01]}
      />
      <mesh
        geometry={nodes.A.geometry}
        material={materials["Number plate"]}
        position={[0, 0.44, 0.01]}
      />
      <mesh
        geometry={nodes.O.geometry}
        material={materials["Number plate"]}
        position={[0.2, 0.37, 0.01]}
      />
      <mesh
        geometry={nodes.Y.geometry}
        material={materials["Number plate"]}
        position={[0.2, 0.3, 0.01]}
      />
      <mesh
        geometry={nodes.DecalAlphabet_W.geometry}
        material={materials["Decal number plate"]}
        position={[0.1, 0, 0]}
      />
      <mesh
        geometry={nodes.DecalNumber_0.geometry}
        material={materials["Decal number plate"]}
        position={[0.35, 0.21, 0]}
      />
      <mesh
        geometry={nodes.DecalNumber_6.geometry}
        material={materials["Decal number plate"]}
        position={[0.2, 0.21, 0]}
      />
      <mesh
        geometry={nodes.DecalAlphabet_D.geometry}
        material={materials["Decal number plate"]}
        position={[0.15, 0.14, 0]}
      />
      <mesh
        geometry={nodes.DecalAlphabet_B.geometry}
        material={materials["Decal number plate"]}
        position={[0.05, 0.14, 0]}
      />
      <mesh
        geometry={nodes.DecalAlphabet_H.geometry}
        material={materials["Decal number plate"]}
        position={[0.35, 0.14, 0]}
      />
      <mesh
        geometry={nodes.DecalAlphabet_I.geometry}
        material={materials["Decal number plate"]}
        position={[0.4, 0.14, 0]}
      />
      <mesh
        geometry={nodes.DecalAlphabet_L.geometry}
        material={materials["Decal number plate"]}
        position={[0.05, 0.07, 0]}
      />
      <mesh
        geometry={nodes.DecalAlphabet_S.geometry}
        material={materials["Decal number plate"]}
        position={[0.4, 0.07, 0]}
      />
      <mesh
        geometry={nodes.DecalAlphabet_V.geometry}
        material={materials["Decal number plate"]}
        position={[0.05, 0, 0]}
      />
      <mesh
        geometry={nodes.DecalNumber_5.geometry}
        material={materials["Decal number plate"]}
        position={[0.16, 0.21, 0]}
      />
      <mesh
        geometry={nodes.DecalAlphabet_A.geometry}
        material={materials["Decal number plate"]}
        position={[0, 0.14, 0]}
      />
      <mesh
        geometry={nodes.DecalAlphabet_R.geometry}
        material={materials["Decal number plate"]}
        position={[0.35, 0.07, 0]}
      />
      <mesh
        geometry={nodes.DecalAlphabet_N.geometry}
        material={materials["Decal number plate"]}
        position={[0.15, 0.07, 0]}
      />
      <mesh
        geometry={nodes.DecalAlphabet_Q.geometry}
        material={materials["Decal number plate"]}
        position={[0.3, 0.07, 0]}
      />
      <mesh
        geometry={nodes.DecalAlphabet_Y.geometry}
        material={materials["Decal number plate"]}
        position={[0.2, 0, 0]}
      />
      <mesh
        geometry={nodes.DecalNumber_3.geometry}
        material={materials["Decal number plate"]}
        position={[0.08, 0.21, 0]}
      />
      <mesh
        geometry={nodes.DecalAlphabet_J.geometry}
        material={materials["Decal number plate"]}
        position={[0.45, 0.14, 0]}
      />
      <mesh
        geometry={nodes.DecalAlphabet_T.geometry}
        material={materials["Decal number plate"]}
        position={[0.45, 0.07, 0]}
      />
      <mesh
        geometry={nodes.DecalNumber_1.geometry}
        material={materials["Decal number plate"]}
        position={[0, 0.21, 0]}
      />
      <mesh
        geometry={nodes.DecalNumber_4.geometry}
        material={materials["Decal number plate"]}
        position={[0.12, 0.21, 0]}
      />
      <mesh
        geometry={nodes.DecalAlphabet_G.geometry}
        material={materials["Decal number plate"]}
        position={[0.3, 0.14, 0]}
      />
      <mesh
        geometry={nodes.DecalAlphabet_O.geometry}
        material={materials["Decal number plate"]}
        position={[0.2, 0.07, 0]}
      />
      <mesh
        geometry={nodes.DecalAlphabet_Z.geometry}
        material={materials["Decal number plate"]}
        position={[0.25, 0, 0]}
      />
      <mesh
        geometry={nodes.DecalNumber_7.geometry}
        material={materials["Decal number plate"]}
        position={[0.24, 0.21, 0]}
      />
      <mesh
        geometry={nodes.DecalAlphabet_C.geometry}
        material={materials["Decal number plate"]}
        position={[0.1, 0.14, 0]}
      />
      <mesh
        geometry={nodes.DecalAlphabet_E.geometry}
        material={materials["Decal number plate"]}
        position={[0.2, 0.14, 0]}
      />
      <mesh
        geometry={nodes.DecalAlphabet_F.geometry}
        material={materials["Decal number plate"]}
        position={[0.25, 0.14, 0]}
      />
      <mesh
        geometry={nodes.DecalAlphabet_K.geometry}
        material={materials["Decal number plate"]}
        position={[0, 0.07, 0]}
      />
      <mesh
        geometry={nodes.DecalAlphabet_P.geometry}
        material={materials["Decal number plate"]}
        position={[0.25, 0.07, 0]}
      />
      <mesh
        geometry={nodes.DecalAlphabet_U.geometry}
        material={materials["Decal number plate"]}
      />
      <mesh
        geometry={nodes.DecalAlphabet_X.geometry}
        material={materials["Decal number plate"]}
        position={[0.15, 0, 0]}
      />
      <mesh
        geometry={nodes.DecalNumber_9.geometry}
        material={materials["Decal number plate"]}
        position={[0.31, 0.21, 0]}
      />
      <mesh
        geometry={nodes.DecalAlphabet_M.geometry}
        material={materials["Decal number plate"]}
        position={[0.1, 0.07, 0]}
      />
      <mesh
        geometry={nodes.DecalNumber_2.geometry}
        material={materials["Decal number plate"]}
        position={[0.04, 0.21, 0]}
      />
      <mesh
        geometry={nodes.DecalNumber_8.geometry}
        material={materials["Decal number plate"]}
        position={[0.27, 0.21, 0]}
      />
    </group>
  );
}

useGLTF.preload(
  "/alphabet.gltf"
);
